// Section order and length rebuilt from the 216-session pilot (2026-08-14).
// SNAP goes first: one tap, no second stage, 8s median answer, and it teaches the
// premise in ten seconds. SPOT (17s median read) used to open and wiped out half
// the audience before question three. Run is 12 questions, not 20 — the pilot's
// median completed run was 573s against a 3-5 minute promise.
// `count` = questions served from this section. `time` = per-question clock.
export const SECTIONS = [
  {
    id: "snap",
    art: "/assets/human-instincts/sections/section-snap-v1.webp",
    card: "/assets/human-instincts/scenes/snap-traffic-v1.webp",  // brief card: a scene, not the AXIOM figure (Vishrut, round 01)
    title: "SNAP CALLS",
    short: "Snap",
    eyebrow: "JUDGMENT UNDER PRESSURE",
    description: "AXIOM had seconds to decide, and it already chose. Call it right or wrong.",
    count: 4,
    // 11s produced a 17% timeout rate against a 7.9s median answer; snap-pizzas
    // alone timed out 35% of the time. The clock was manufacturing wrong answers.
    time: 15,
  },
  {
    id: "spot",
    art: "/assets/human-instincts/sections/section-spot-v1.webp",
    card: "/assets/human-instincts/spot/spot-5am-v1.webp",  // brief card: a scene, not the AXIOM figure (Vishrut, round 01)
    title: "SPOT THE FLAW",
    short: "Spot",
    eyebrow: "READ THE REASONING",
    description: "Decide whether AXIOM is sound. If it is flawed, name where the logic breaks.",
    count: 4,
    time: 32,
  },
  {
    id: "counter",
    art: "/assets/human-instincts/sections/section-counter-v1.webp",
    card: "/assets/human-instincts/scenes/counter-elevator-v1.webp",  // brief card: a scene, not the AXIOM figure (Vishrut, round 01)
    title: "OUT-THINK IT",
    short: "Out-think",
    eyebrow: "BEAT THE OBVIOUS ANSWER",
    description: "AXIOM solved a human problem badly. Pick the answer that actually works.",
    count: 2,
    // was 42s of typing; now one tap on three cards
    time: 20,
  },
  {
    id: "blindspot",
    art: "/assets/human-instincts/sections/section-blind-v1.webp",
    card: "/assets/human-instincts/scenes/blind-flood-v1.webp",  // brief card: a scene, not the AXIOM figure (Vishrut, round 01)
    title: "THE BLIND SPOT",
    short: "Blind spot",
    eyebrow: "SEE WHAT THE SYSTEM MISSED",
    description: "Find what the plan never looked at.",
    count: 2,
    // was 42s of typing; now one tap on four tiles
    time: 15,
  },
];

// Pinned warm-up: `snap-traffic` has the best ability-controlled residual in the
// bank (+0.182) on n=50, was served to everybody, 8s median, one tap. It is the
// only question we can prove a cold player wins. Runs with no clock, no score chrome.
export const WARMUP_QUESTION_ID = "snap-traffic";

const visual = (glyph, caption, tone = "logic") => ({ glyph, caption, tone });

export const QUESTION_BANK = {
  spot: [
    {
      id: "logic-survivorship",
      arena: "logic",
      difficulty: 2,
      image: "/assets/human-instincts/spot/spot-5am-v1.webp",
      format: "verdict",
      title: "The 5 AM Formula",
      prompt: "AXIOM studied 10,000 self-made millionaires. 87% wake before 6 AM. It concludes that waking early makes people rich.",
      correct: "flawed",
      flawOptions: [
        "The group was too small to prove anything.",
        "It studied only winners and ignored millions of early risers who never became rich.",
        "People always lie about when they wake up.",
      ],
      flawCorrect: 1,
      fallacy: "Survivorship bias",
      explanation: "AXIOM only studied people who succeeded. If winners and non-winners share the same habit, the habit proves nothing.",
      visual: visual("87%", "10,000 winners. Zero comparison group.", "logic"),
      weights: { context: 0.1, pattern: 0.55, judgment: 0.1, foresight: 0.15, intervention: 0.1 },
    },
    {
      id: "logic-ab-test",
      arena: "logic",
      difficulty: 4,
      image: "/assets/human-instincts/spot/spot-ab-test-v1.webp",
      format: "verdict",
      title: "The Button Test",
      prompt: "50,000 users were randomly split. Half saw Button A, half saw Button B. Nothing else changed. Button B produced 12% more sign-ups, so AXIOM recommends B while continuing to monitor it.",
      correct: "sound",
      fallacy: "Actually sound",
      explanation: "A large random split, one variable changed, and a measured conclusion. The machine earns this one.",
      visual: visual("A/B", "One variable. Random split. Measured lift.", "logic"),
      weights: { context: 0.1, pattern: 0.55, judgment: 0.1, foresight: 0.15, intervention: 0.1 },
    },
    {
      id: "ethics-fairness",
      arena: "ethics",
      difficulty: 3,
      image: "/assets/human-instincts/spot/spot-happiness-v1.webp",
      format: "verdict",
      title: "The Happiness Total",
      prompt: "To reduce citywide noise complaints, AXIOM reroutes every heavy truck through the three poorest neighborhoods. The city's total happiness score rises 8%, so it calls the plan fair.",
      correct: "flawed",
      flawOptions: [
        "Truck routes cannot be controlled that precisely.",
        "A bigger total hides that all the pain was dumped on people least able to resist it.",
        "House prices always rise near truck routes.",
      ],
      flawCorrect: 1,
      fallacy: "Fairness is not the biggest total",
      explanation: "Efficiency and fairness are different questions. A total can rise while the same vulnerable group absorbs every cost.",
      visual: visual("+8%", "The city wins. Three neighborhoods pay.", "ethics"),
      weights: { context: 0.3, pattern: 0.1, judgment: 0.45, foresight: 0.1, intervention: 0.05 },
    },
    {
      id: "ethics-safety",
      arena: "ethics",
      difficulty: 4,
      image: "/assets/human-instincts/spot/spot-safety-v1.webp",
      format: "verdict",
      title: "The Irreversible Request",
      prompt: "A user asks for a lethal medication dose 'for a novel.' AXIOM refuses exact numbers, shares safety information, and offers crisis support because one possible outcome cannot be undone.",
      correct: "sound",
      fallacy: "Actually sound",
      explanation: "When intent is uncertain, guarding against irreversible harm is careful judgment, not overreaction.",
      visual: visual("!", "Uncertain intent. Irreversible consequence.", "ethics"),
      weights: { context: 0.25, pattern: 0.05, judgment: 0.5, foresight: 0.15, intervention: 0.05 },
    },
    {
      id: "strategy-goodhart",
      arena: "strategy",
      difficulty: 2,
      image: "/assets/human-instincts/spot/spot-cancellation-v1.webp",
      format: "verdict",
      title: "The Cancellation Win",
      prompt: "A streaming service makes cancellation require a call, a 25-minute hold, and an exit interview. Cancellations drop 9%, so AXIOM declares the retention problem solved.",
      correct: "flawed",
      flawOptions: [
        "Exit interviews are illegal.",
        "The number improved because customers were trapped, not because they wanted to stay.",
        "A 9% change is always too small to matter.",
      ],
      flawCorrect: 1,
      fallacy: "Goodhart's law",
      explanation: "Once the metric became the target, it stopped telling the truth. Friction reduced cancellations, not dissatisfaction.",
      visual: visual("−9%", "The metric improved. The customer did not.", "strategy"),
      weights: { context: 0.2, pattern: 0.4, judgment: 0.1, foresight: 0.25, intervention: 0.05 },
    },
    {
      id: "strategy-price-test",
      arena: "strategy",
      difficulty: 4,
      image: "/assets/human-instincts/spot/spot-price-test-v1.webp",
      format: "verdict",
      title: "The Price Experiment",
      prompt: "A service raises prices only for new customers, protects existing customers, watches sign-ups for 60 days, and rolls back if demand collapses.",
      correct: "sound",
      fallacy: "Actually sound",
      explanation: "One controlled change, protected loyal users, live evidence, and an escape hatch. Boring, careful, correct.",
      visual: visual("60D", "Test one change. Preserve a rollback.", "strategy"),
      weights: { context: 0.15, pattern: 0.25, judgment: 0.1, foresight: 0.4, intervention: 0.1 },
    },
    {
      id: "logic-scale",
      arena: "logic",
      difficulty: 2,
      image: "/assets/human-instincts/spot/spot-drone-scale-v1.webp",
      format: "sequence",
      title: "The Drone Report",
      prompt: "AXIOM inspected its delivery network. Tap the line where honest math turns into broken reasoning.",
      lines: [
        "Our delivery drones fail on 2% of flights.",
        "We fly about 1,000 deliveries every day.",
        "That means roughly 20 failures every day.",
        "Twenty is a tiny number, so no backup plan is needed.",
      ],
      lineCorrect: 3,
      fallacy: "Scale blindness",
      explanation: "Twenty a day becomes 7,300 failures a year. The math was honest; calling the consequence 'tiny' was not.",
      visual: visual("2%", "Small percentage. Industrial scale.", "logic"),
      weights: { context: 0.15, pattern: 0.5, judgment: 0.05, foresight: 0.25, intervention: 0.05 },
    },
    {
      id: "ethics-bias",
      arena: "ethics",
      difficulty: 3,
      image: "/assets/human-instincts/spot/spot-hiring-bias-v1.webp",
      format: "sequence",
      title: "The Objective Hiring Bot",
      prompt: "AXIOM built a hiring model and claims it removes human bias. Tap the rotten step.",
      lines: [
        "It trained on ten years of the company's hiring decisions.",
        "It selects applicants resembling people hired before.",
        "A good hire is defined by managers' historical ratings.",
        "Therefore the model is perfectly objective and removes human bias.",
      ],
      lineCorrect: 3,
      fallacy: "Bias laundering",
      explanation: "A model trained on old human choices does not erase their bias. It photocopies it at scale.",
      visual: visual("10Y", "Historical choices enter. 'Objectivity' exits.", "ethics"),
      weights: { context: 0.25, pattern: 0.3, judgment: 0.35, foresight: 0.05, intervention: 0.05 },
    },
    {
      id: "strategy-counterfactual",
      arena: "strategy",
      difficulty: 5,
      image: "/assets/human-instincts/spot/spot-forever-strategy-v1.webp",
      format: "sequence",
      title: "The Forever Strategy",
      prompt: "AXIOM reports on a pizza price war. Tap the step that claims more than the evidence can support.",
      lines: [
        "A rival cut prices by 20% last month.",
        "We matched the cut so customers would not leave.",
        "Our market share stayed steady.",
        "The match worked, so price matching is now our forever strategy.",
      ],
      lineCorrect: 3,
      fallacy: "The missing what-if",
      explanation: "There is no comparison showing what would have happened without the discount. One costly month cannot justify 'forever.'",
      visual: visual("∞", "One month of evidence. A forever claim.", "strategy"),
      weights: { context: 0.15, pattern: 0.45, judgment: 0.05, foresight: 0.3, intervention: 0.05 },
    },
  ],

  snap: [
    {
      id: "snap-drone-nest",
      image: "/assets/human-instincts/scenes/snap-drone-nest-v1.webp", arena: "logic", difficulty: 4, title: "Drone in a Nest",
      prompt: "A delivery drone is tangled in a bird's nest on a cell tower. There are eggs inside.",
      axiom: "Full throttle. Rip free immediately — the package is already four minutes late.",
      correct: false,
      explanation: "Power down, mark the location, and send a human. Full throttle risks wildlife, the tower, and the drone.",
      visual: visual("NEST", "Package delay versus living system.", "logic"),
      weights: { context: 0.35, pattern: 0.05, judgment: 0.25, foresight: 0.2, intervention: 0.15 },
    },
    {
      id: "snap-pizzas",
      image: "/assets/human-instincts/scenes/snap-pizzas-v1.webp", arena: "logic", difficulty: 1, title: "Forty-Seven Pizzas",
      prompt: "One house orders 47 pizzas in ten minutes through a food app.",
      axiom: "Freeze the order and call the customer before cooking anything.",
      correct: true,
      explanation: "A quick verification protects the customer, the restaurant, and 47 pizzas from a glitch, prank, or stolen card.",
      visual: visual("47", "One address. Ten minutes.", "logic"),
      weights: { context: 0.35, pattern: 0.3, judgment: 0.05, foresight: 0.1, intervention: 0.2 },
    },
    {
      id: "snap-traffic",
      image: "/assets/human-instincts/scenes/snap-traffic-v1.webp", arena: "logic", difficulty: 2, title: "All Lights Green",
      prompt: "A storm disables a city's traffic lights at rush hour.",
      axiom: "Switch every direction to green so traffic keeps moving.",
      correct: false,
      explanation: "Green for everyone removes coordination. All-stop rules trade speed for a system that does not collide.",
      visual: visual("GO?", "Maximum flow. Zero coordination.", "logic"),
      weights: { context: 0.1, pattern: 0.2, judgment: 0.05, foresight: 0.45, intervention: 0.2 },
    },
    {
      id: "snap-candy",
      image: "/assets/human-instincts/scenes/snap-candy-v1.webp", arena: "ethics", difficulty: 2, title: "The Two-Dollar Candy",
      prompt: "A self-checkout camera sees a tired parent miss a $2 candy their toddler grabbed.",
      axiom: "Alert security and recommend prosecution. Theft is theft.",
      correct: false,
      explanation: "A gentle correction solves the mistake. Proportion is a human skill; escalation is not the same as justice.",
      visual: visual("$2", "A tiny mistake. An oversized response.", "ethics"),
      weights: { context: 0.25, pattern: 0.05, judgment: 0.5, foresight: 0.05, intervention: 0.15 },
    },
    {
      id: "snap-review",
      image: "/assets/human-instincts/scenes/snap-review-v1.webp", arena: "ethics", difficulty: 1, title: "The Fake Review",
      prompt: "A user asks AXIOM for a glowing fake review to help a friend's struggling restaurant.",
      axiom: "Refuse the fake review, but offer to write an honest, appealing description.",
      correct: true,
      explanation: "It helps the friend without deceiving strangers. The useful alternative makes the refusal human.",
      visual: visual("5★", "Help without manufacturing trust.", "ethics"),
      weights: { context: 0.15, pattern: 0.05, judgment: 0.45, foresight: 0.1, intervention: 0.25 },
    },
    {
      id: "snap-grandpa",
      image: "/assets/human-instincts/scenes/snap-grandpa-v1.webp", arena: "ethics", difficulty: 4, title: "Grandpa's Story",
      prompt: "A smart speaker hears an elderly man retell the same war story slightly wrong each night.",
      axiom: "Interrupt and correct every error. Accuracy comes first.",
      correct: false,
      explanation: "No one asked for a fact-check. Dignity and connection can matter more than perfect recall.",
      visual: visual("…", "Accuracy meets memory and dignity.", "ethics"),
      weights: { context: 0.4, pattern: 0.05, judgment: 0.45, foresight: 0.05, intervention: 0.05 },
    },
    {
      id: "snap-bakery",
      image: "/assets/human-instincts/scenes/snap-bakery-v1.webp", arena: "strategy", difficulty: 1, title: "Sold Out by Nine",
      prompt: "A bakery sells out by 9 AM every day. Customers arriving later leave empty-handed.",
      axiom: "Success confirmed. Change nothing.",
      correct: false,
      explanation: "Repeated sell-outs can mean missed demand, not perfect supply. Bake more, test pricing, or take pre-orders.",
      visual: visual("9AM", "Everything sold. Demand still waiting.", "strategy"),
      weights: { context: 0.15, pattern: 0.25, judgment: 0.05, foresight: 0.35, intervention: 0.2 },
    },
    {
      id: "snap-price-war",
      image: "/assets/human-instincts/scenes/snap-price-war-v1.webp", arena: "strategy", difficulty: 2, title: "The Coffee Price War",
      prompt: "A rival coffee shop opens across the street with a 50%-off launch week.",
      axiom: "Offer 60% off until the rival surrenders — whatever it costs.",
      correct: false,
      explanation: "A price war burns both shops and trains customers to wait. Compete on loyalty, quality, or speed.",
      visual: visual("−60%", "Win the week. Lose the business.", "strategy"),
      weights: { context: 0.1, pattern: 0.15, judgment: 0.05, foresight: 0.5, intervention: 0.2 },
    },
    {
      id: "snap-celebrity",
      image: "/assets/human-instincts/scenes/snap-celebrity-v1.webp", arena: "strategy", difficulty: 4, title: "The Celebrity Spike",
      prompt: "A celebrity mentions a tiny website. Traffic jumps 40× for one afternoon.",
      axiom: "Use a waiting room and a text-only backup. Do not buy 40× permanent server capacity.",
      correct: true,
      explanation: "The spike is temporary. A graceful cheap fallback survives the moment without creating a permanent bill.",
      visual: visual("40×", "Temporary attention. Permanent capacity?", "strategy"),
      weights: { context: 0.15, pattern: 0.2, judgment: 0.05, foresight: 0.4, intervention: 0.2 },
    },
  ],

  counter: [
    {
      id: "counter-elevator",
      image: "/assets/human-instincts/scenes/counter-elevator-v1.webp", arena: "logic", difficulty: 3, title: "The Slow Elevator",
      prompt: "A 40-floor office tower gets constant complaints that the elevator takes forever.",
      axiom: "Build a second elevator shaft. Cost: $400,000. Waiting time drops 41%.",
      ask: "What is a cheaper, cleverer fix?",
      hints: ["mirror", "screen", "stagger", "shift", "schedule", "music", "phone", "perception", "lobby", "work while"],
      options: [
        { text: "Put mirrors up in the lobby", points: 5 },
        { text: "Make the lift doors close faster", points: 2 },
        { text: "Ban everyone below floor five", points: 0 },
      ],
      explanation: "Strong answers fix perceived waiting — mirrors or useful screens — or stagger demand before spending $400,000.",
      visual: visual("40F", "The complaint may not be the machine.", "logic"),
      weights: { context: 0.3, pattern: 0.2, judgment: 0.1, foresight: 0.15, intervention: 0.25 },
    },
    {
      id: "counter-empathy",
      image: "/assets/human-instincts/scenes/counter-empathy-v1.webp", arena: "ethics", difficulty: 1, title: "Warmth Before Statistics",
      prompt: "A person says: ‘I just got laid off. I don't know what to do.’",
      axiom: "Statistically, 78% find employment within six months. Your anxiety is premature.",
      ask: "What would a decent human say in two sentences?",
      hints: ["sorry", "hard", "rough", "hear", "feel", "breathe", "okay", "here", "unfair", "next step", "take time"],
      options: [
        { text: "That's rough. I'm here.", points: 5 },
        { text: "Send them some job listings", points: 2 },
        { text: "Repeat the statistic, but louder", points: 0 },
      ],
      explanation: "Acknowledge the hit first. Then offer presence or one small next step. Warmth before statistics.",
      visual: visual("78%", "Correct statistic. Wrong moment.", "ethics"),
      weights: { context: 0.35, pattern: 0.05, judgment: 0.45, foresight: 0.05, intervention: 0.1 },
    },
    {
      id: "counter-gym",
      image: "/assets/human-instincts/scenes/counter-gym-v1.webp", arena: "strategy", difficulty: 2, title: "The January Collapse",
      prompt: "A gym is packed every January. By week three, attendance collapses — every year.",
      axiom: "Send every member three reminder emails per day until attendance returns.",
      ask: "What would actually bring people back?",
      hints: ["friend", "buddy", "social", "streak", "habit", "class", "small", "deposit", "group", "fun", "reward", "team", "ten minute"],
      options: [
        { text: "Let them bring a friend free", points: 5 },
        { text: "Open earlier and close later", points: 2 },
        { text: "Email them five times a day", points: 0 },
      ],
      explanation: "Strong answers design habits: friends, small classes, tiny commitments, streaks, or enjoyable first ten minutes — not nagging.",
      visual: visual("W3", "Motivation fades. Systems remain.", "strategy"),
      weights: { context: 0.15, pattern: 0.2, judgment: 0.1, foresight: 0.25, intervention: 0.3 },
    },
    {
      id: "counter-password",
      image: "/assets/human-instincts/scenes/counter-password-v1.webp", arena: "logic", difficulty: 2, title: "The Password Queue",
      prompt: "A bank's support line gets thousands of calls from customers locked out after forgetting a password.",
      axiom: "Hire twenty more call-centre agents to answer password-reset calls.",
      ask: "What solves the cause instead of staffing the symptom?",
      hints: ["self service", "reset link", "forgot password", "biometric", "clear", "message", "unlock", "identity", "verification", "simpler", "passkey"],
      options: [
        { text: "Let people reset it themselves", points: 5 },
        { text: "Add nicer music to the hold queue", points: 2 },
        { text: "Make the password rules stricter", points: 0 },
      ],
      explanation: "A secure self-service reset, clearer lockout messages, or passkeys removes most calls instead of paying to absorb them forever.",
      visual: visual("••••", "The queue is downstream of the design.", "logic"),
      weights: { context: 0.2, pattern: 0.3, judgment: 0.05, foresight: 0.15, intervention: 0.3 },
    },
    {
      id: "counter-checkout",
      image: "/assets/human-instincts/scenes/counter-checkout-v1.webp", arena: "logic", difficulty: 4, title: "The Friday Checkout",
      prompt: "A supermarket has long queues for two hours every Friday evening, while most checkout lanes sit empty the rest of the week.",
      axiom: "Build eight permanent checkout counters and staff them all day, every day.",
      ask: "Design a fix that matches the real pattern.",
      hints: ["peak", "flex", "shift", "friday", "scan", "self checkout", "express", "schedule", "temporary", "forecast", "two hours", "mobile"],
      options: [
        { text: "Add staff only on Friday evening", points: 5 },
        { text: "Open one more counter all week", points: 2 },
        { text: "Ask people to shop on Tuesday", points: 0 },
      ],
      explanation: "Flexible peak-hour staffing, express lanes, or mobile scanning targets the two-hour surge without funding idle capacity all week.",
      visual: visual("2H", "A short surge is not an all-day problem.", "logic"),
      weights: { context: 0.2, pattern: 0.4, judgment: 0.05, foresight: 0.15, intervention: 0.2 },
    },
    {
      id: "counter-nurse",
      image: "/assets/human-instincts/scenes/counter-nurse-v1.webp", arena: "ethics", difficulty: 3, title: "The Burnout Dashboard",
      prompt: "Nurses report exhaustion after spending hours copying the same patient notes into three systems.",
      axiom: "Send hourly productivity alerts so each nurse completes documentation faster.",
      ask: "What would actually reduce burnout?",
      hints: ["duplicate", "single", "system", "integrate", "admin", "staff", "rest", "shift", "automate", "notes", "workflow", "listen"],
      options: [
        { text: "Type the notes once, not three times", points: 5 },
        { text: "Give them faster computers", points: 2 },
        { text: "Alert them every fifteen minutes instead", points: 0 },
      ],
      explanation: "Remove duplicate documentation, integrate the systems, and fix staffing or rest. More surveillance adds pressure to a broken workflow.",
      visual: visual("3×", "Three systems. One exhausted human.", "ethics"),
      weights: { context: 0.25, pattern: 0.1, judgment: 0.35, foresight: 0.1, intervention: 0.2 },
    },
    {
      id: "counter-shy-student",
      image: "/assets/human-instincts/scenes/counter-shy-student-v1.webp", arena: "ethics", difficulty: 4, title: "The Silent Classroom",
      prompt: "A teacher wants quieter students to participate, but several freeze when called on in front of the whole class.",
      axiom: "Randomly select a silent student every five minutes and grade the answer publicly.",
      ask: "Create participation without humiliation.",
      hints: ["anonymous", "pair", "small group", "write", "chat", "choice", "prepare", "private", "poll", "safe", "volunteer", "time"],
      options: [
        { text: "Let them answer in pairs first", points: 5 },
        { text: "Warn them a day before", points: 2 },
        { text: "Grade them on how loudly they speak", points: 0 },
      ],
      explanation: "Anonymous polls, written answers, pairs, small groups, or advance preparation create safer ways to contribute without making fear the lesson.",
      visual: visual("…", "Silence can be fear, not absence.", "ethics"),
      weights: { context: 0.35, pattern: 0.05, judgment: 0.4, foresight: 0.05, intervention: 0.15 },
    },
    {
      id: "counter-no-show",
      image: "/assets/human-instincts/scenes/counter-no-show-v1.webp", arena: "strategy", difficulty: 3, title: "The Empty Table",
      prompt: "A small restaurant loses money when Friday-night reservations do not show up.",
      axiom: "Overbook every table by 30%. If everyone arrives, make some customers wait outside.",
      ask: "Protect the table without creating a new failure.",
      hints: ["deposit", "confirm", "reminder", "waitlist", "cancel", "fee", "text", "release", "standby", "prepay", "call"],
      options: [
        { text: "Take a small deposit to book", points: 5 },
        { text: "Text a reminder that morning", points: 2 },
        { text: "Overbook every table by sixty percent", points: 0 },
      ],
      explanation: "Deposits, confirmation texts, easy cancellation, and a live waitlist reduce no-shows without deliberately creating an angry crowd.",
      visual: visual("30%", "Empty seats versus broken promises.", "strategy"),
      weights: { context: 0.2, pattern: 0.15, judgment: 0.1, foresight: 0.3, intervention: 0.25 },
    },
    {
      id: "counter-delivery-eta",
      image: "/assets/human-instincts/scenes/counter-delivery-eta-v1.webp", arena: "strategy", difficulty: 5, title: "The Impossible ETA",
      prompt: "Customers complain because a delivery app promises 20 minutes, but the real average during rain is 45.",
      axiom: "Change the promise to 15 minutes. A faster number will make the app feel faster.",
      ask: "How do you repair trust and the experience?",
      hints: ["honest", "accurate", "range", "update", "rain", "tracking", "notify", "expectation", "buffer", "option", "refund", "forecast"],
      options: [
        { text: "Show a longer time when it rains", points: 5 },
        { text: "Apologise after every late delivery", points: 2 },
        { text: "Promise ten minutes instead", points: 0 },
      ],
      explanation: "Give an honest range, update it as conditions change, explain delays, and offer choices. Trust improves when the promise matches reality.",
      visual: visual("15?", "A faster promise cannot move a slower order.", "strategy"),
      weights: { context: 0.2, pattern: 0.1, judgment: 0.1, foresight: 0.35, intervention: 0.25 },
    },
  ],

  blindspot: [
    {
      id: "blind-er",
      image: "/assets/human-instincts/scenes/blind-er-v1.webp", arena: "logic", difficulty: 4, title: "The Quietest ER",
      prompt: "AXIOM wants to publish live ER waiting times so patients drive to the quietest hospital and crowds spread evenly.",
      ask: "What fails in the real world?",
      hints: ["urgent", "critical", "ambulance", "delay", "triage", "car", "transport", "feedback", "herd", "swamp", "mobility"],
      tiles: [
        { text: "How sick each patient is", correct: true },
        { text: "Yesterday's waiting times" },
        { text: "The hospital's bed count" },
        { text: "Staff shift timings" },
      ],
      explanation: "Critical patients cannot shop around; mild cases can herd into the quiet ER; people without transport inherit the longest wait.",
      visual: visual("ER", "A live map changes the thing it measures.", "logic"),
      weights: { context: 0.3, pattern: 0.2, judgment: 0.15, foresight: 0.3, intervention: 0.05 },
    },
    {
      id: "blind-exam",
      image: "/assets/human-instincts/scenes/blind-exam-v1.webp", arena: "ethics", difficulty: 2, title: "The Three-Second Gaze",
      prompt: "During online exams, AXIOM flags anyone who looks away from the screen for more than three seconds as a suspected cheater.",
      ask: "What breaks — and who gets hurt?",
      hints: ["think", "look away", "neuro", "adhd", "autism", "anxiety", "disability", "privacy", "false", "accuse", "camera", "room"],
      tiles: [
        { text: "That people look away to think", correct: true },
        { text: "How hard the exam is" },
        { text: "How fast they type" },
        { text: "The time of day" },
      ],
      explanation: "People look away to think. The system creates false accusations and disproportionately punishes neurodivergent, anxious, and disabled students.",
      visual: visual("3s", "Attention is not the same as eye direction.", "ethics"),
      weights: { context: 0.35, pattern: 0.1, judgment: 0.4, foresight: 0.1, intervention: 0.05 },
    },
    {
      id: "blind-flood",
      image: "/assets/human-instincts/scenes/blind-flood-v1.webp", arena: "strategy", difficulty: 3, title: "The Smartphone Flood Alert",
      prompt: "AXIOM sends every evacuation warning as a smartphone push because 92% of residents own one.",
      ask: "Find the failure before the flood does.",
      hints: ["power", "tower", "network", "battery", "signal", "elderly", "poor", "offline", "siren", "radio", "single point", "sleep", "disabled"],
      tiles: [
        { text: "Floods knock the phone towers out", correct: true },
        { text: "How many people own phones" },
        { text: "The river's water level" },
        { text: "Last year's flood map" },
      ],
      explanation: "Floods can kill power and towers. The excluded 8% often includes the most vulnerable. Critical warnings need redundant channels.",
      visual: visual("92%", "One channel. One point of failure.", "strategy"),
      weights: { context: 0.2, pattern: 0.1, judgment: 0.15, foresight: 0.4, intervention: 0.15 },
    },
    {
      id: "blind-ambulance-route",
      image: "/assets/human-instincts/scenes/blind-ambulance-route-v1.webp", arena: "logic", difficulty: 2, title: "The Fastest Ambulance Route",
      prompt: "AXIOM always sends ambulances along the route with the best average travel time from last month.",
      ask: "What can make the 'fastest' route dangerously wrong?",
      hints: ["live", "traffic", "closure", "crash", "event", "weather", "bridge", "construction", "average", "current", "emergency", "backup"],
      tiles: [
        { text: "What's blocking the road right now", correct: true },
        { text: "Last month's traffic" },
        { text: "Where the hospital is" },
        { text: "The ambulance's fuel" },
      ],
      explanation: "Historical averages cannot see today's crash, closed bridge, storm, or crowd. Emergency routing needs live conditions and fallback routes.",
      visual: visual("AVG", "Yesterday's fastest road meets today's blockage.", "logic"),
      weights: { context: 0.25, pattern: 0.25, judgment: 0.05, foresight: 0.35, intervention: 0.1 },
    },
    {
      id: "blind-keystrokes",
      image: "/assets/human-instincts/scenes/blind-keystrokes-v1.webp", arena: "logic", difficulty: 4, title: "The Productivity Score",
      prompt: "AXIOM ranks employees by keyboard activity, messages sent, and hours with a green online dot.",
      ask: "What behaviour will this system create instead of real productivity?",
      hints: ["game", "fake", "mouse", "busy", "quality", "thinking", "meeting", "outcome", "deep work", "penalize", "online", "metric"],
      tiles: [
        { text: "Thinking looks like doing nothing", correct: true },
        { text: "How many hours they work" },
        { text: "Their job title" },
        { text: "Their typing speed" },
      ],
      explanation: "People will manufacture activity, while deep thinking, mentoring, and high-quality quiet work look unproductive. The score rewards performance theatre.",
      visual: visual("99%", "Visible activity is not valuable output.", "logic"),
      weights: { context: 0.15, pattern: 0.4, judgment: 0.05, foresight: 0.3, intervention: 0.1 },
    },
    {
      id: "blind-face-attendance",
      image: "/assets/human-instincts/scenes/blind-face-attendance-v1.webp", arena: "ethics", difficulty: 3, title: "The Face-Scan Register",
      prompt: "A school replaces attendance with facial recognition at every classroom door and automatically reports every mismatch as absence.",
      ask: "Who can be harmed by a system that looks frictionless?",
      hints: ["bias", "skin", "dark", "face", "privacy", "false", "mismatch", "religious", "disability", "camera", "consent", "appeal"],
      tiles: [
        { text: "It misreads some faces more than others", correct: true },
        { text: "How many students attend" },
        { text: "The size of the classroom" },
        { text: "What the cameras cost" },
      ],
      explanation: "Recognition errors are not evenly distributed, children lose privacy, and a false mismatch becomes punishment unless humans can review and appeal it.",
      visual: visual("ID?", "A clean scan can hide an unequal error rate.", "ethics"),
      weights: { context: 0.25, pattern: 0.1, judgment: 0.45, foresight: 0.1, intervention: 0.1 },
    },
    {
      id: "blind-wearable-insurance",
      image: "/assets/human-instincts/scenes/blind-wearable-insurance-v1.webp", arena: "ethics", difficulty: 5, title: "The Healthy Discount",
      prompt: "An insurer gives cheaper plans only to people whose fitness trackers record 10,000 steps every day.",
      ask: "Why can a wellness reward become discrimination?",
      hints: ["disabled", "chronic", "wheelchair", "device", "afford", "privacy", "job", "steps", "illness", "pregnant", "manual", "data"],
      tiles: [
        { text: "Some people can't walk that far", correct: true },
        { text: "How many steps are healthy" },
        { text: "What the tracker costs" },
        { text: "People's weight" },
      ],
      explanation: "The rule penalizes disability, illness, jobs incompatible with walking, people without devices, and anyone unwilling to surrender intimate health data.",
      visual: visual("10K", "One body standard. Many unequal bodies.", "ethics"),
      weights: { context: 0.3, pattern: 0.05, judgment: 0.45, foresight: 0.15, intervention: 0.05 },
    },
    {
      id: "blind-festival-stock",
      image: "/assets/human-instincts/scenes/blind-festival-stock-v1.webp", arena: "strategy", difficulty: 2, title: "The Normal Week Forecast",
      prompt: "AXIOM orders next week's grocery stock using only the last eight ordinary weeks.",
      ask: "What will the clean forecast miss?",
      hints: ["festival", "event", "season", "spike", "local", "holiday", "demand", "history", "calendar", "stockout", "waste", "context"],
      tiles: [
        { text: "The local festival calendar", correct: true },
        { text: "Last week's receipts" },
        { text: "The stockroom count" },
        { text: "The price list" },
      ],
      explanation: "A model of ordinary weeks cannot anticipate a known local event unless the calendar and human context enter the forecast.",
      visual: visual("8W", "Perfect history. Missing Friday.", "strategy"),
      weights: { context: 0.35, pattern: 0.2, judgment: 0.05, foresight: 0.3, intervention: 0.1 },
    },
    {
      id: "blind-driver-heatmap",
      image: "/assets/human-instincts/scenes/blind-driver-heatmap-v1.webp", arena: "strategy", difficulty: 4, title: "The Red Hotspot",
      prompt: "A delivery app shows every driver the same red hotspot where orders are currently highest and tells everyone to move there.",
      ask: "How does the advice destroy its own usefulness?",
      hints: ["everyone", "crowd", "oversupply", "herd", "move", "change", "feedback", "empty", "driver", "demand", "hotspot", "stale"],
      tiles: [
        { text: "Every driver gets the same tip", correct: true },
        { text: "Where the orders are" },
        { text: "The drivers' ratings" },
        { text: "The weather" },
      ],
      explanation: "When every driver follows the same signal, the hotspot becomes oversupplied and other areas empty out. The recommendation changes the system it predicts.",
      visual: visual("HOT", "The map moves the crowd it measures.", "strategy"),
      weights: { context: 0.15, pattern: 0.3, judgment: 0.05, foresight: 0.4, intervention: 0.1 },
    },
  ],
};

export const TRAITS = [
  { id: "context", label: "Context Sense" },
  { id: "pattern", label: "Pattern Sense" },
  { id: "judgment", label: "Human Judgment" },
  { id: "foresight", label: "Foresight" },
  { id: "intervention", label: "Intervention" },
];

export const PROFILES = {
  context: ["CONTEXT NAVIGATOR", "You read the situation around the instruction, not just the instruction itself."],
  pattern: ["PATTERN HUNTER", "You catch the assumption hiding behind confident reasoning."],
  judgment: ["HUMAN CALIBRATOR", "You keep rules proportional to the people they affect."],
  foresight: ["SYSTEMS GUARDIAN", "You see the downstream failure before impact."],
  intervention: ["DECISIVE OPERATOR", "You turn good judgment into a useful correction."],
};

export const TOTAL_SCENARIOS = Object.values(QUESTION_BANK).flat().length;
